<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup Label="Compilation">
    <TargetFrameworks>netstandard2.0;netstandard2.1;net462;net8.0;net9.0</TargetFrameworks>
    <RootNamespace>NerdyDuck.CodedExceptions</RootNamespace>
    <AssemblyName>$(RootNamespace)</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup Label="Assembly info">
    <AssemblyTitle>NerdyDuck CodedExceptions</AssemblyTitle>
    <Description>Exceptions with custom HRESULTs to identify the origins of errors.</Description>
  </PropertyGroup>
  <PropertyGroup Label="NuGet package settings">
    <PackageReleaseNotes>
      - Upgraded target frameworks to .NET 8/9, .NET Standard 2.0/2.1 and .NET Framework 4.6.2
      - Switched license from Apache 2.0 to MIT.
      - Split Configuration namespace into three separate library packages.
      - Changed German resources from de-DE to just de.
      - Updated all signatures for nullability.
      - Added new exceptions and throw helper methods.
    </PackageReleaseNotes>
    <PackageTags>Exception HRESULT</PackageTags>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="contentFiles/**/*">
      <PackagePath>contentFiles</PackagePath>
      <BuildAction>Compile</BuildAction>
    </Content>
  </ItemGroup>
</Project>
