//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NerdyDuck.CodedExceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NerdyDuck.CodedExceptions.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (&apos;{1}&apos;) must be equal to &apos;{2}&apos;..
        /// </summary>
        internal static string ArgumentOutOfRange_MustBeEqual {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_MustBeEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (&apos;{1}&apos;) must be greater than &apos;{2}&apos;..
        /// </summary>
        internal static string ArgumentOutOfRange_MustBeGreater {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_MustBeGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (&apos;{1}&apos;) must be greater than or equal to &apos;{2}&apos;..
        /// </summary>
        internal static string ArgumentOutOfRange_MustBeGreaterOrEqual {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_MustBeGreaterOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (&apos;{1}&apos;) must be less than &apos;{2}&apos;..
        /// </summary>
        internal static string ArgumentOutOfRange_MustBeLess {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_MustBeLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (&apos;{1}&apos;) must be less than or equal to &apos;{2}&apos;..
        /// </summary>
        internal static string ArgumentOutOfRange_MustBeLessOrEqual {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_MustBeLessOrEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (&apos;{1}&apos;) must be a multiple of &apos;{2}&apos;..
        /// </summary>
        internal static string ArgumentOutOfRange_MustBeMultiple {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_MustBeMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (&apos;{1}&apos;) must be a non-negative value..
        /// </summary>
        internal static string ArgumentOutOfRange_MustBeNonNegative {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_MustBeNonNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (&apos;{1}&apos;) must be a non-negative and non-zero value..
        /// </summary>
        internal static string ArgumentOutOfRange_MustBeNonNegativeNonZero {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_MustBeNonNegativeNonZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (&apos;{1}&apos;) must be a non-zero value..
        /// </summary>
        internal static string ArgumentOutOfRange_MustBeNonZero {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_MustBeNonZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (&apos;{1}&apos;) must not be equal to &apos;{2}&apos;..
        /// </summary>
        internal static string ArgumentOutOfRange_MustBeNotEqual {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_MustBeNotEqual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (&apos;{1}&apos;) must not be less than &apos;{2}&apos; or greater than &apos;{3}&apos;..
        /// </summary>
        internal static string ArgumentOutOfRange_MustNotBeOutOfRange {
            get {
                return ResourceManager.GetString("ArgumentOutOfRange_MustNotBeOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version number part of assembly identifier is invalid..
        /// </summary>
        internal static string AssemblyIdentifier_VersionInvalid {
            get {
                return ResourceManager.GetString("AssemblyIdentifier_VersionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The public key token part of assembly identifier is invalid..
        /// </summary>
        internal static string AssemblyIdentity_KeyTokenInvalid {
            get {
                return ResourceManager.GetString("AssemblyIdentity_KeyTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly has no name..
        /// </summary>
        internal static string AssemblyIdentity_NoAssemblyName {
            get {
                return ResourceManager.GetString("AssemblyIdentity_NoAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}---&amp;gt; (Inner exception #{2}) {3}&amp;lt;---{1}.
        /// </summary>
        internal static string CodedAggregateException_ToString {
            get {
                return ResourceManager.GetString("CodedAggregateException_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be an empty string..
        /// </summary>
        internal static string CodedArgumentException_EmptyMessage {
            get {
                return ResourceManager.GetString("CodedArgumentException_EmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value cannot be an empty string or composed entirely of whitespace..
        /// </summary>
        internal static string CodedArgumentException_WhitespaceMessage {
            get {
                return ResourceManager.GetString("CodedArgumentException_WhitespaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be null or an empty string..
        /// </summary>
        internal static string CodedArgumentNullOrEmptyException_Message {
            get {
                return ResourceManager.GetString("CodedArgumentNullOrEmptyException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be null or empty, or contains only white-space characters..
        /// </summary>
        internal static string CodedArgumentNullOrWhiteSpaceException_Message {
            get {
                return ResourceManager.GetString("CodedArgumentNullOrWhiteSpaceException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data is invalid..
        /// </summary>
        internal static string CodedDataException_Message {
            get {
                return ResourceManager.GetString("CodedDataException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the specified directory..
        /// </summary>
        internal static string CodedDirectoryNotFoundException_Message {
            get {
                return ResourceManager.GetString("CodedDirectoryNotFoundException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find directory &apos;{0}&apos;..
        /// </summary>
        internal static string CodedDirectoryNotFoundException_MessageDirectory {
            get {
                return ResourceManager.GetString("CodedDirectoryNotFoundException_MessageDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file already exists..
        /// </summary>
        internal static string CodedFileExistsException_Message {
            get {
                return ResourceManager.GetString("CodedFileExistsException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; already exists..
        /// </summary>
        internal static string CodedFileExistsException_MessageFile {
            get {
                return ResourceManager.GetString("CodedFileExistsException_MessageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file is invalid..
        /// </summary>
        internal static string CodedInvalidFileException_Message {
            get {
                return ResourceManager.GetString("CodedInvalidFileException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string CodedInvalidFileException_MessageFile {
            get {
                return ResourceManager.GetString("CodedInvalidFileException_MessageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A socket error occurred..
        /// </summary>
        internal static string CodedSocketException_Message {
            get {
                return ResourceManager.GetString("CodedSocketException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Socket error: {0} ({0:d})).
        /// </summary>
        internal static string CodedSocketException_ToString_SocketErrorCode {
            get {
                return ResourceManager.GetString("CodedSocketException_ToString_SocketErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serialized data does not contain an object of type AssemblyIdentifier..
        /// </summary>
        internal static string ctor_NotAssemblyIdentifier {
            get {
                return ResourceManager.GetString("ctor_NotAssemblyIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility id must range between 0 and 2047..
        /// </summary>
        internal static string FacilityId_OutOfRange {
            get {
                return ResourceManager.GetString("FacilityId_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element &apos;{0}&apos; has no attribute &apos;{1}&apos;..
        /// </summary>
        internal static string FromXml_AttributeMissing {
            get {
                return ResourceManager.GetString("FromXml_AttributeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsEnabled setting of assembly &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string FromXml_IsEnabledInvalid {
            get {
                return ResourceManager.GetString("FromXml_IsEnabledInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory name: &apos;{0}&apos;.
        /// </summary>
        internal static string Global_DirectoryName {
            get {
                return ResourceManager.GetString("Global_DirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name: &apos;{0}&apos;.
        /// </summary>
        internal static string Global_FileName {
            get {
                return ResourceManager.GetString("Global_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a hexadecimal digit..
        /// </summary>
        internal static string HexToInt_InvalidChar {
            get {
                return ResourceManager.GetString("HexToInt_InvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough free space in data storage..
        /// </summary>
        internal static string InsufficientStorageSpaceException_Message {
            get {
                return ResourceManager.GetString("InsufficientStorageSpaceException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough free space in data storage &apos;{0}&apos;..
        /// </summary>
        internal static string InsufficientStorageSpaceException_MessagePath {
            get {
                return ResourceManager.GetString("InsufficientStorageSpaceException_MessagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly name &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string Load_AssemblyNameInvalid {
            get {
                return ResourceManager.GetString("Load_AssemblyNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String may not be null or empty..
        /// </summary>
        internal static string Load_NullOrEmpty {
            get {
                return ResourceManager.GetString("Load_NullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open file &apos;{0}&apos; for reading..
        /// </summary>
        internal static string Load_OpenFileFailed {
            get {
                return ResourceManager.GetString("Load_OpenFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support reading..
        /// </summary>
        internal static string Load_StreamNoRead {
            get {
                return ResourceManager.GetString("Load_StreamNoRead", resourceCulture);
            }
        }
    }
}
