//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NerdyDuck.CodedExceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NerdyDuck.CodedExceptions.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version number part of assembly identifier is invalid..
        /// </summary>
        internal static string AssemblyIdentifier_ctor_VersionInvalid {
            get {
                return ResourceManager.GetString("AssemblyIdentifier_ctor_VersionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The public key token part of assembly identifier is invalid..
        /// </summary>
        internal static string AssemblyIdentity_ctor_KeyTokenInvalid {
            get {
                return ResourceManager.GetString("AssemblyIdentity_ctor_KeyTokenInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly has no name..
        /// </summary>
        internal static string AssemblyIdentity_ctor_NoAssemblyName {
            get {
                return ResourceManager.GetString("AssemblyIdentity_ctor_NoAssemblyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}{1}---&gt; (Inner exception #{2}) {3}&lt;---{1}.
        /// </summary>
        internal static string CodedAggregateException_ToString {
            get {
                return ResourceManager.GetString("CodedAggregateException_ToString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be null or empty..
        /// </summary>
        internal static string CodedArgumentNullOrEmptyException_Message {
            get {
                return ResourceManager.GetString("CodedArgumentNullOrEmptyException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Argument cannot be null or empty, or contains only white-space characters..
        /// </summary>
        internal static string CodedArgumentNullOrWhiteSpaceException_Message {
            get {
                return ResourceManager.GetString("CodedArgumentNullOrWhiteSpaceException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data is invalid..
        /// </summary>
        internal static string CodedDataException_Message {
            get {
                return ResourceManager.GetString("CodedDataException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find the specified directory..
        /// </summary>
        internal static string CodedDirectoryNotFoundException_Message {
            get {
                return ResourceManager.GetString("CodedDirectoryNotFoundException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find directory &apos;{0}&apos;..
        /// </summary>
        internal static string CodedDirectoryNotFoundException_MessageDirectory {
            get {
                return ResourceManager.GetString("CodedDirectoryNotFoundException_MessageDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file already exists..
        /// </summary>
        internal static string CodedFileExistsException_Message {
            get {
                return ResourceManager.GetString("CodedFileExistsException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; already exists..
        /// </summary>
        internal static string CodedFileExistsException_MessageFile {
            get {
                return ResourceManager.GetString("CodedFileExistsException_MessageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified file is invalid..
        /// </summary>
        internal static string CodedInvalidFileException_Message {
            get {
                return ResourceManager.GetString("CodedInvalidFileException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string CodedInvalidFileException_MessageFile {
            get {
                return ResourceManager.GetString("CodedInvalidFileException_MessageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A socket error occurred..
        /// </summary>
        internal static string CodedSocketException_Message {
            get {
                return ResourceManager.GetString("CodedSocketException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Socket error: {0} ({0:d})).
        /// </summary>
        internal static string CodedSocketException_ToString_SocketErrorCode {
            get {
                return ResourceManager.GetString("CodedSocketException_ToString_SocketErrorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly name &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string Global_AssemblyNameInvalid {
            get {
                return ResourceManager.GetString("Global_AssemblyNameInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serialized data does not contain an object of type AssemblyIdentifier..
        /// </summary>
        internal static string Global_ctor_MissingAssemblyIdentifier {
            get {
                return ResourceManager.GetString("Global_ctor_MissingAssemblyIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory name: &apos;{0}&apos;.
        /// </summary>
        internal static string Global_DirectoryName {
            get {
                return ResourceManager.GetString("Global_DirectoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facility id must range between 0 and 2047..
        /// </summary>
        internal static string Global_FacilityId_OutOfRange {
            get {
                return ResourceManager.GetString("Global_FacilityId_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name: &apos;{0}&apos;.
        /// </summary>
        internal static string Global_FileName {
            get {
                return ResourceManager.GetString("Global_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element &apos;{0}&apos; has no attribute &apos;{1}&apos;..
        /// </summary>
        internal static string Global_FromXml_AttributeMissing {
            get {
                return ResourceManager.GetString("Global_FromXml_AttributeMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier override of assembly &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string Global_IdentifierInvalid {
            get {
                return ResourceManager.GetString("Global_IdentifierInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsEnabled setting of assembly &apos;{0}&apos; is invalid..
        /// </summary>
        internal static string Global_IsEnabledInvalid {
            get {
                return ResourceManager.GetString("Global_IsEnabledInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Content may not be null, empty or white-space only..
        /// </summary>
        internal static string Global_NoContent {
            get {
                return ResourceManager.GetString("Global_NoContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path may not be null, empty or white-space only..
        /// </summary>
        internal static string Global_NoPath {
            get {
                return ResourceManager.GetString("Global_NoPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot open file &apos;{0}&apos; for reading..
        /// </summary>
        internal static string Global_OpenFileFailed {
            get {
                return ResourceManager.GetString("Global_OpenFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stream does not support reading..
        /// </summary>
        internal static string Global_StreamNoRead {
            get {
                return ResourceManager.GetString("Global_StreamNoRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a hexadecimal digit..
        /// </summary>
        internal static string HResultHelper_HexToInt_InvalidChar {
            get {
                return ResourceManager.GetString("HResultHelper_HexToInt_InvalidChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough free space in data storage..
        /// </summary>
        internal static string InsufficientStorageSpaceException_Message {
            get {
                return ResourceManager.GetString("InsufficientStorageSpaceException_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough free space in data storage &quot;{0}&quot;..
        /// </summary>
        internal static string InsufficientStorageSpaceException_MessagePath {
            get {
                return ResourceManager.GetString("InsufficientStorageSpaceException_MessagePath", resourceCulture);
            }
        }
    }
}
