<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Condition="'$(IsTestProject)' == 'false'">
    <ArtifactsProjectName>assemblies</ArtifactsProjectName>
  </PropertyGroup>
  <PropertyGroup Condition="'$(IsTestProject)' == 'true'">
    <ArtifactsProjectName>test</ArtifactsProjectName>
  </PropertyGroup>
  <PropertyGroup>
    <ArtifactsProjectName Condition="'$(Configuration)' != ''">$(ArtifactsProjectName)\$(Configuration.ToLowerInvariant())</ArtifactsProjectName>
    <ArtifactsProjectName>$(ArtifactsProjectName)\$(MSBuildProjectName)</ArtifactsProjectName>
    <ArtifactsPivots Condition="'$(TargetFrameworks)' != '' And '$(TargetFramework)' != ''">$(TargetFramework.ToLowerInvariant())</ArtifactsPivots>
  </PropertyGroup>
</Project>
