<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />
  <PropertyGroup Label="Compilation">
    <IsTestProject>false</IsTestProject>
    <OutputType>Library</OutputType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <DefineTrace>true</DefineTrace>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
    <Nullable>enable</Nullable>
    <ArtifactsBinOutputName>bin\output</ArtifactsBinOutputName>
    <ArtifactsPivots>$(Configuration.ToLowerInvariant())\$(TargetFramework.ToLowerInvariant())</ArtifactsPivots>
  </PropertyGroup>
  <PropertyGroup Label="Code Analysis">
    <AnalysisMode>AllEnabledByDefault</AnalysisMode>
  </PropertyGroup>
  <PropertyGroup Label="Assembly Signing">
    <SignAssembliesAndPackage>false</SignAssembliesAndPackage>
    <NoWarn>NU3043</NoWarn>
  </PropertyGroup>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('signing.props', '$(MSBuildThisFileDirectory)../'))" Condition="$([MSBuild]::GetPathOfFileAbove('signing.props', '$(MSBuildThisFileDirectory)../')) != ''" />
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <SignAssembliesAndPackage>false</SignAssembliesAndPackage>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <CreateGitHubZip>false</CreateGitHubZip>
    <DefineDebug>true</DefineDebug>
    <DebugType>Full</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <SignAssembliesAndPackage>true</SignAssembliesAndPackage>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <CreateGitHubZip>true</CreateGitHubZip>
    <DefineDebug>false</DefineDebug>
    <DebugType>Portable</DebugType>
  </PropertyGroup>
  <PropertyGroup Label="NuGet package settings">
    <IsPackable>true</IsPackable>
    <PackageOutputPath>$(ArtifactsPath)/NuGet/$(Configuration)/</PackageOutputPath>
    <MinClientVersion>6.0</MinClientVersion>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <Authors>Daniel Kopp</Authors>
    <PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageIcon>NerdyDuck.CodedExceptions-128x128.png</PackageIcon>
    <PackageProjectUrl>https://github.com/NerdyDuck/NerdyDuck.CodedExceptions</PackageProjectUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>readme.md</PackageReadmeFile>
  </PropertyGroup>
  <PropertyGroup Label="Github Release Zips">
    <ZipOutputPath>$(ArtifactsPath)/Zip/</ZipOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NuGet.Build.Tasks.Pack">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
  <ItemGroup Label="NuGet package items">
    <None Include="$(MSBuildThisFileDirectory)../media/NerdyDuck.CodedExceptions-128x128.png" Pack="true" PackagePath="\">
      <Link>NerdyDuck.CodedExceptions-128x128.png</Link>
    </None>
    <None Include="readme.md" Pack="true" PackagePath="\"/>
  </ItemGroup>
  <ItemGroup Label="Global code">
    <Compile Include="$(MSBuildThisFileDirectory)shared/*.cs" />
  </ItemGroup>
</Project>
