<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ItemGroup>
    <Compile Update="SR.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>SR.resx</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="SR.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>SR.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <Import Project="$([MSBuild]::GetPathOfFileAbove('signing.targets', '$(MSBuildThisFileDirectory)../'))" Condition="$([MSBuild]::GetPathOfFileAbove('signing.targets', '$(MSBuildThisFileDirectory)../')) != ''" />
  <Target Name="CreateGitHubZip" BeforeTargets="Pack" Condition=" '$(CreateGitHubZip)' == 'true' ">
    <MakeDir Directories="$(ZipOutputPath)"/>
    <ZipDirectory SourceDirectory="$(OutputPath)" DestinationFile="$(ZipOutputPath)$(AssemblyName)-$(Version)-binaries.zip" Overwrite="true" />
  </Target>
  <Target Name="CleanZip" AfterTargets="Clean" Condition=" '$(CreateGitHubZip)' == 'true' ">
    <ItemGroup>
      <_ZipToDelete Include="$(PackageOutputPath)$(AssemblyName)-$(Version)-binaries.zip" />
    </ItemGroup>
    <Delete Files="@(_ZipToDelete)"/>
  </Target>
  <Target Name="UpdateInformationalVersions" BeforeTargets="GetAssemblyVersion">
    <CreateProperty Value="$(Version)$(PrereleaseVersion)">
      <Output TaskParameter="Value" PropertyName="InformationalVersion"/>
    </CreateProperty>
  </Target>
  <Target Name="UpdatePackageVersions" BeforeTargets="GenerateNuspec">
    <CreateProperty Value="$(Version)$(PrereleaseVersion)">
      <Output TaskParameter="Value" PropertyName="PackageVersion"/>
    </CreateProperty>
    <Message Text="PackageVersion: $(PackageVersion)" Importance="high" />
  </Target>
  <Target Name="ClearReferenceCopyLocalPaths" AfterTargets="ResolveAssemblyReferences" Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'">
    <ItemGroup>
      <ReferenceCopyLocalPaths Remove="@(ReferenceCopyLocalPaths)" />
    </ItemGroup>
  </Target>
</Project>
