#Region "Copyright"
'*******************************************************************************
' <copyright file="AssemblyInfo.vb" owner="Daniel Kopp">
' Copyright 2015 Daniel Kopp
'
' Licensed under the Apache License, Version 2.0 (the "License");
' you may Not use this file except in compliance with the License.
' You may obtain a copy of the License at
'
'     http://www.apache.org/licenses/LICENSE-2.0
'
' Unless required by applicable law Or agreed to in writing, software
' distributed under the License Is distributed on an "AS IS" BASIS,
' WITHOUT WARRANTIES Or CONDITIONS OF ANY KIND, either express Or implied.
' See the License for the specific language governing permissions And
' limitations under the License.
' </copyright>
' <author name = "Daniel Kopp" email="dak@nerdyduck.de" />
' <assembly name="ExampleCsharpDesktop">
' Example for NerdyDuck.CodedExceptions - Desktop version
' </assembly>
' <file name="AssemblyInfo.vb" date="2015-09-21">
' Contains assembly-level properties.
' </file>
'******************************************************************************/
#End Region

Imports NerdyDuck.CodedExceptions
Imports System.Reflection

' General Information
<Assembly: AssemblyTitle("ExampleVBDesktop")>
<Assembly: AssemblyDescription("Example for NerdyDuck.CodedExceptions - Desktop version")>
<Assembly: AssemblyCompany("NerdyDuck")>
<Assembly: AssemblyProduct("NerdyDuck Core Libraries")>
<Assembly: AssemblyCopyright("Copyright © Daniel Kopp 2015")>
<Assembly: AssemblyTrademark("Covered by Apache License 2.0")>

<Assembly: AssemblyVersion("1.0.0.0")>
<Assembly: AssemblyFileVersion("1.0.0.0")>

' The facility identifier for all exceptions generated by the assembly
<Assembly: AssemblyFacilityIdentifier(&H0042)>
